// getAll
GET http://localhost:3001/api/persons

###

// getInfo
GET http://localhost:3001/info

###

// getSingle
GET http://localhost:3001/api/persons/64be1441aa82447373e6bcfd

###

// deletePerson
DELETE http://localhost:3001/api/persons/64be1441aa82447373e6bcfd

###

// addNewPerson
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Marek Testowy",
    "number": "111-21362"
}

###

// updatePerson
PUT http://localhost:3001/api/persons/64be142faa82447373e6bcf9
Content-Type: application/json

{
    "name": "j",
    "number": "111-222-333"
}