// getAll
GET http://localhost:3001/api/persons

###

// getInfo
GET http://localhost:3001/info

###

// getSingle
GET http://localhost:3001/api/persons/64be1441aa82447373e6bcfd

###

// deletePerson
DELETE http://localhost:3001/api/persons/64be12f00d159632ca72e4d3

###

// addNewPerson
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Jan Test",
    "number": "111-222-333"
}

###

// updatePerson
PUT http://localhost:3001/api/persons/64be12f00d159632ca72e4d3
Content-Type: application/json

{
    "name": "Adam Update-Test",
    "number": "111-222-333"
}